### ISSUE TITLE
display the possible directions in the rooms

### ISSUE THREAD

**Issue by ChristophSchauer** [ChristophSchauer/RPG-Ratten#13]

**Comment by MalevolentGoat** [comment]
Doors are now shown

TODO: Enhance System with hidden doors

**Comment by ChristophSchauer** [comment]
could append it to list for every door like 'opened/locked'

```
22:{ "name" : "corridor",
                 "west" : [21,'opened'],
                 "south": [24,'opened', 'hidden'],
                 "up"   : [32,'locked'],
                 "item" : ["torch"],
                 "person": ["fledermaus",1]},
```

like in 22[south]

**Comment by MalevolentGoat** [comment]
Hidden Doors are now hidden correctly, but can be entered -> walking against a door you can't see should not be an option

**Comment by ChristophSchauer** [comment]
before the user enters the new room, check in the fct_move if the door is hidden, if hidden the user can't go into this direction.
