### ISSUE TITLE
Add Triggered Events

### ISSUE THREAD

**Issue by MalevolentGoat** [ChristophSchauer/RPG-Ratten#19]
ie. written text on wall, only visible if torch in inventory

**Comment by MalevolentGoat** [comment]
We need 2 different kinds of triggered events:
- [x] Upon entering a room (too dark without torch)
- [x] Using certain items in certain rooms

**Comment by ChristophSchauer** [comment]
An extra function, which is called when move[1]=='go' would make sense. And this function handles the properties (dark, hidden things, ....) of the rooms under consideration of the inventory.

**Comment by MalevolentGoat** [comment]
One can now enter a dark room but won't be able to pick things up nor see them, except if using a torch, which is destroyed in the process

**Comment by ChristophSchauer** [comment]
Would be better if the user could decide, if he wants to let the torch in the room. If yes, then the room is set alight and the torch is deleted from the inventory and can be seen as item in the room. If the player says no, the torch remains in the inventory and the room gets dark when the player leaves the room.

**Comment by MalevolentGoat** [comment]
Not using a torch means it isn't yet set on fire, so one wouldn't see anything. Therefor the torch is used in the process anyway. Room should get dark again after leaving.

Fix Uploaded: Torch redesign, using a torch means igniting it for 3 rounds, getting used up in the process

TODO: room-details not shown if dark
