### ISSUE TITLE
set up handling system

### ISSUE THREAD

**Issue by ChristophSchauer** [ChristophSchauer/RPG-Ratten#27]
@MalevolentGoat : I think about putting the files on the dropbox, because this one updates the folders automatically. Under consideration of Flo, which has deactivated automatic start when Windows is started, Github is preferred because we don't have to copy paste the issues from an external list;

testers would be:
- Flo
- Patrick
- Steffi
- Gerfried
- Alex
- Vuko
- ... anyone else?

**Comment by MalevolentGoat** [comment]
What? Can you be more cryptic pls?

**Comment by ChristophSchauer** [comment]
should we let everything run over github or save the exe and a xls for bugs on the dropbox?
